### PR TITLE
Fix broken Windows build

### PR DESCRIPTION
**Pull request by dechamps**
The regression was introduced in commit 4314df644e22778a554ca1760941a2bfae08bce2.

      CC       tincctl.o
    tincctl.c: In function ‘connect_tincd’:
    tincctl.c:724:21: warning: implicit declaration of function ‘kill’ [-Wimplicit-function-declaration]
      if ((pid == 0) || (kill(pid, 0) && (errno == ESRCH))) {
	        	     ^~~~
      CCLD     tinc.exe
    tincctl.o: In function `connect_tincd':
    /home/e-t172/dev/tinc/src/tincctl.c:724: undefined reference to `kill'
    collect2: error: ld returned 1 exit status
    Makefile:830: recipe for target 'tinc.exe' failed

### CODE REVIEW

**Comment by gsliepen** [comment]
Ugh, I just fixed this myself while your patch has been lying around here since forever. Sorry for not applying it earlier!
