### ISSUE TITLE
Compilation broken under MinGW

### ISSUE THREAD

**Issue by wolfy1339** [gsliepen/tinc#239]
Commit f5223937e62e1cc5e9b3d322490dd3af8d666750 (Introduced by #234) breaks compilation under MinGW because it looks for a header which does not exist under MinGW.

fd_device.c:24:10: fatal error: sys/un.h: No such file or directory
 #include <sys/un.h>
          ^~~~~~~~~~

**Comment by wolfy1339** [comment]
Should be fixed by 6061f6bf59cadce7f26164f7a8ec9923438d223c
